/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author hesac
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainView() {
        
        initComponents();
        initView();
        setLayout(new GridLayout(1, 1));
        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    public JPanel getDonBaoDuongPanel() {
        return DonBaoDuongPanel;
    }

    public void setDonBaoDuongPanel(JPanel DonBaoDuongPanel) {
        this.DonBaoDuongPanel = DonBaoDuongPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DonBaoDuongPanel = new View.DonBaoDuongPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DonBaoDuongPanel.setPreferredSize(new java.awt.Dimension(1900, 1000));
        DonBaoDuongPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DonBaoDuongPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DonBaoDuongPanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DonBaoDuongPanelLayout = new javax.swing.GroupLayout(DonBaoDuongPanel);
        DonBaoDuongPanel.setLayout(DonBaoDuongPanelLayout);
        DonBaoDuongPanelLayout.setHorizontalGroup(
            DonBaoDuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1900, Short.MAX_VALUE)
        );
        DonBaoDuongPanelLayout.setVerticalGroup(
            DonBaoDuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DonBaoDuongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DonBaoDuongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DonBaoDuongPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonBaoDuongPanelMouseEntered
        DonBaoDuongPanel d = (DonBaoDuongPanel) DonBaoDuongPanel;
        d.setBackground(Color.gray);

    }//GEN-LAST:event_DonBaoDuongPanelMouseEntered

    private void DonBaoDuongPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonBaoDuongPanelMouseExited
        DonBaoDuongPanel.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_DonBaoDuongPanelMouseExited

    private void initView() {
        DonBaoDuongPanel.setLayout(new GridLayout(1, 4));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DonBaoDuongPanel;
    // End of variables declaration//GEN-END:variables
}
